name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to the main branch, change if your main branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Hugo
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.104.3+extended'  # specify the Hugo version you're using

    # Step 3: Build the site
    - name: Build the Hugo site
      run: hugo --minify  # You can add any other Hugo build flags here

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Hugo's output folder
        publish_branch: gh-pages  # The branch where you want to deploy the site
